# Generated by Django 6.0.3 on 2026-04-17 19:45

import uuid
from django.db import migrations, models


def generate_uuids(apps, schema_editor):
    Comment = apps.get_model("softdesksupport", "Comment")
    for comment in Comment.objects.all():
        comment.uuid = uuid.uuid4()
        comment.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("softdesksupport", "0002_issue_type"),
    ]

    operations = [
        # Étape 1 : ajouter le champ sans contrainte unique
        migrations.AddField(
            model_name="comment",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="UUID du commentaire"
            ),
        ),
        # Étape 2 : peupler avec des UUIDs uniques
        migrations.RunPython(generate_uuids, migrations.RunPython.noop),
        # Étape 3 : ajouter la contrainte unique
        migrations.AlterField(
            model_name="comment",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="UUID du commentaire",
            ),
        ),
    ]
