# Generated by Django 6.0.3 on 2026-04-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesksupport', '0003_add_comment_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
